export type Permission = {
  name: string;
  description: string;
  resource: string;
  action: string;
};

export const PERMISSIONS: Permission[] = [
  {
    name: "users.create",
    description: "Create users",
    resource: "users",
    action: "create",
  },
  {
    name: "users.read",
    description: "Read users",
    resource: "users",
    action: "read",
  },
  {
    name: "users.update",
    description: "Update users",
    resource: "users",
    action: "update",
  },
  {
    name: "users.delete",
    description: "Delete users",
    resource: "users",
    action: "delete",
  },
  {
    name: "students.create",
    description: "Create student records",
    resource: "students",
    action: "create",
  },
  {
    name: "students.read",
    description: "Read student records",
    resource: "students",
    action: "read",
  },
  {
    name: "students.update",
    description: "Update student records",
    resource: "students",
    action: "update",
  },
  {
    name: "students.delete",
    description: "Delete student records",
    resource: "students",
    action: "delete",
  },
  {
    name: "students.promote",
    description: "Promote students",
    resource: "students",
    action: "promote",
  },
  {
    name: "students.graduate",
    description: "Graduate students",
    resource: "students",
    action: "graduate",
  },
  {
    name: "students.import",
    description: "Import students",
    resource: "students",
    action: "import",
  },
  {
    name: "teachers.create",
    description: "Create teacher records",
    resource: "teachers",
    action: "create",
  },
  {
    name: "teachers.read",
    description: "Read teacher records",
    resource: "teachers",
    action: "read",
  },
  {
    name: "teachers.update",
    description: "Update teacher records",
    resource: "teachers",
    action: "update",
  },
  {
    name: "teachers.delete",
    description: "Delete teacher records",
    resource: "teachers",
    action: "delete",
  },
  {
    name: "teachers.assign_class",
    description: "Assign teachers to classes",
    resource: "teachers",
    action: "assign_class",
  },
  {
    name: "teachers.assign_subject",
    description: "Assign teachers to subjects",
    resource: "teachers",
    action: "assign_subject",
  },
  {
    name: "classes.manage",
    description: "Manage classes",
    resource: "classes",
    action: "manage",
  },
  {
    name: "majors.manage",
    description: "Manage majors",
    resource: "majors",
    action: "manage",
  },
  {
    name: "subjects.manage",
    description: "Manage subjects",
    resource: "subjects",
    action: "manage",
  },
  {
    name: "semesters.manage",
    description: "Manage semesters",
    resource: "semesters",
    action: "manage",
  },
  {
    name: "enrollments.create",
    description: "Create enrollments",
    resource: "enrollments",
    action: "create",
  },
  {
    name: "enrollments.read",
    description: "Read enrollments",
    resource: "enrollments",
    action: "read",
  },
  {
    name: "enrollments.update",
    description: "Update enrollments",
    resource: "enrollments",
    action: "update",
  },
  {
    name: "enrollments.delete",
    description: "Delete enrollments",
    resource: "enrollments",
    action: "delete",
  },
  {
    name: "grades.input",
    description: "Input grades",
    resource: "grades",
    action: "input",
  },
  {
    name: "grades.read",
    description: "Read grades",
    resource: "grades",
    action: "read",
  },
  {
    name: "grades.read_any",
    description: "Read any grades",
    resource: "grades",
    action: "read_any",
  },
  {
    name: "grades.read_own",
    description: "Read own grades",
    resource: "grades",
    action: "read_own",
  },
  {
    name: "grades.print",
    description: "Print grade reports",
    resource: "grades",
    action: "print",
  },
  {
    name: "grades.approve",
    description: "Approve grades",
    resource: "grades",
    action: "approve",
  },
  {
    name: "announcements.create",
    description: "Create announcements",
    resource: "announcements",
    action: "create",
  },
  {
    name: "announcements.read",
    description: "Read announcements",
    resource: "announcements",
    action: "read",
  },
  {
    name: "announcements.update",
    description: "Update announcements",
    resource: "announcements",
    action: "update",
  },
  {
    name: "announcements.delete",
    description: "Delete announcements",
    resource: "announcements",
    action: "delete",
  },
  {
    name: "announcements.publish",
    description: "Publish announcements",
    resource: "announcements",
    action: "publish",
  },
  {
    name: "documents.create",
    description: "Upload documents (RPP)",
    resource: "documents",
    action: "create",
  },
  {
    name: "documents.read",
    description: "Read documents",
    resource: "documents",
    action: "read",
  },
  {
    name: "documents.review_rpp",
    description: "Review RPP documents",
    resource: "documents",
    action: "review_rpp",
  },
  {
    name: "payments.create",
    description: "Create payments",
    resource: "payments",
    action: "create",
  },
  {
    name: "payments.read_any",
    description: "Read any payments",
    resource: "payments",
    action: "read_any",
  },
  {
    name: "payments.read_own",
    description: "Read own payments",
    resource: "payments",
    action: "read_own",
  },
  {
    name: "payments.update",
    description: "Update payments",
    resource: "payments",
    action: "update",
  },
  {
    name: "payments.approve",
    description: "Approve payments",
    resource: "payments",
    action: "approve",
  },
  {
    name: "payments.generate_report",
    description: "Generate payment reports",
    resource: "payments",
    action: "generate_report",
  },
  {
    name: "payment_methods.manage",
    description: "Manage payment methods",
    resource: "payment_methods",
    action: "manage",
  },
  {
    name: "system_configs.manage",
    description: "Manage system configs",
    resource: "system_configs",
    action: "manage",
  },
  {
    name: "profile.edit_own",
    description: "Edit own profile",
    resource: "profile",
    action: "edit_own",
  },
  {
    name: "profile.edit_any",
    description: "Edit any profile",
    resource: "profile",
    action: "edit_any",
  },
  {
    name: "profile.assets.upload",
    description: "Upload profile assets",
    resource: "profile",
    action: "assets_upload",
  },
  {
    name: "calendar.read",
    description: "Read calendar events",
    resource: "calendar",
    action: "read",
  },
  {
    name: "calendar.manage",
    description: "Manage calendar events",
    resource: "calendar",
    action: "manage",
  },
];

export type RoleEntry = {
  name: string;
  description: string;
  level: number;
};

export const ROLE_ENTRIES: RoleEntry[] = [
  { name: "superadmin", description: "Full system access", level: 100 },
  { name: "administrator", description: "Admin staff (TU)", level: 80 },
  { name: "guru", description: "Teacher", level: 60 },
  { name: "siswa", description: "Student", level: 40 },
  { name: "alumni", description: "Alumni (read-only)", level: 20 },
];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  superadmin: PERMISSIONS.map((p) => p.name),
  administrator: [
    "users.create",
    "users.read",
    "users.update",
    "students.create",
    "students.read",
    "students.update",
    "students.delete",
    "students.promote",
    "students.graduate",
    "students.import",
    "teachers.create",
    "teachers.read",
    "teachers.update",
    "teachers.delete",
    "teachers.assign_class",
    "teachers.assign_subject",
    "classes.manage",
    "majors.manage",
    "subjects.manage",
    "semesters.manage",
    "enrollments.create",
    "enrollments.read",
    "enrollments.update",
    "enrollments.delete",
    "grades.input",
    "grades.read_any",
    "grades.read_own",
    "grades.print",
    "announcements.create",
    "announcements.read",
    "announcements.update",
    "announcements.delete",
    "announcements.publish",
    "documents.create",
    "documents.read",
    "documents.review_rpp",
    "payments.create",
    "payments.read_any",
    "payments.read_own",
    "payments.update",
    "payments.approve",
    "payments.generate_report",
    "payment_methods.manage",
    "system_configs.manage",
    "profile.edit_own",
    "profile.edit_any",
    "profile.assets.upload",
    "calendar.read",
    "calendar.manage",
  ],
  guru: [
    "grades.input",
    "grades.read_any",
    "students.read",
    "announcements.read",
    "profile.edit_own",
    "subjects.manage",
    "teachers.read",
    "classes.manage",
    "majors.manage",
    "semesters.manage",
    "enrollments.read",
    "calendar.read",
    "documents.create",
    "documents.read",
  ],
  siswa: [
    "grades.read_own",
    "announcements.read",
    "profile.edit_own",
    "students.read",
    "payments.read_own",
    "documents.read",
    "enrollments.read",
    "calendar.read",
  ],
  alumni: ["grades.read_own", "profile.edit_own"],
};
