import { z } from "zod";

export const completeProfileSchema = z.object({
  previousSchool: z.string().max(255).optional().or(z.literal("")),
  nik: z.string().max(255).optional().or(z.literal("")),
  birthPlace: z.string().max(255).optional().or(z.literal("")),
  birthDate: z.string().optional().or(z.literal("")),
  gender: z.enum(["male", "female"]).optional().or(z.literal("")),
  birthOrder: z.string().optional().or(z.literal("")),
  siblingsCount: z.string().optional().or(z.literal("")),
  address: z.string().max(500).optional().or(z.literal("")),
  weightKg: z.string().optional().or(z.literal("")),
  heightCm: z.string().optional().or(z.literal("")),
  phone: z.string().max(30).optional().or(z.literal("")),
  religionId: z.string().optional().or(z.literal("")),
  diplomaNumber: z.string().max(255).optional().or(z.literal("")),
  skhuNumber: z.string().max(255).optional().or(z.literal("")),
  fatherName: z.string().max(255).optional().or(z.literal("")),
  fatherBirthPlace: z.string().max(255).optional().or(z.literal("")),
  fatherBirthDate: z.string().optional().or(z.literal("")),
  fatherNik: z.string().max(255).optional().or(z.literal("")),
  fatherOccupation: z.string().max(255).optional().or(z.literal("")),
  motherName: z.string().max(255).optional().or(z.literal("")),
  motherBirthPlace: z.string().max(255).optional().or(z.literal("")),
  motherBirthDate: z.string().optional().or(z.literal("")),
  motherNik: z.string().max(255).optional().or(z.literal("")),
  motherOccupation: z.string().max(255).optional().or(z.literal("")),
  parentsAddress: z.string().max(500).optional().or(z.literal("")),
  parentsPhone: z.string().max(20).optional().or(z.literal("")),
  majorId: z.string().optional().or(z.literal("")),
  uniformSize: z.string().max(10).optional().or(z.literal("")),
});
